<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../JtlDemo.Abstractions/JtlDemo.Abstractions.csproj" />
  </ItemGroup>

</Project>
