<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../JtlDemo.Rest.Server/JtlDemo.Rest.Server.csproj" />
  </ItemGroup>

</Project>
